### ISSUE TITLE
Segmentation fault after change cuda-based python code to xpu-based python code with codegeex2-6b mode

### ISSUE THREAD

**Issue by ganghe** [intel-analytics/ipex-llm#10296]
Hi Team,

I tried to change codegeex2 cuda-based python example code to xpu-based python code with codegeex2-6b mode file,
but the program always crashed.

The cuda-based python file is here,
https://github.com/THUDM/CodeGeeX2/blob/main/demo/fastapicpu.py

I can run it with cpu device, e.g. "python fastapicpu.py --model-path codegeex2-6b --cpu".
but, I changed cuda-based python code to xpu-based python code, run it with gpu device
with the command as below
source /opt/intel/oneapi/setvars.sh --force
python -X faulthandler fastapicpu.py --model-path codegeex2-6b

Then, the program crashed at line 207, 
"model = model.to('xpu')"

The related files are attached.
fastapicpu.old.txt - cuda based python file
fastapicpu.py.txt   - xpu based python file
cmd.txt - startup command script
output.txt - program output log
mode file - https://hf-mirror.com/THUDM/codegeex2-6b

[cmd.txt](https://github.com/intel-analytics/BigDL/files/14457833/cmd.txt)
[fastapicpu.old.txt](https://github.com/intel-analytics/BigDL/files/14457834/fastapicpu.old.txt)
[fastapicpu.py.txt](https://github.com/intel-analytics/BigDL/files/14457835/fastapicpu.py.txt)
[output.txt](https://github.com/intel-analytics/BigDL/files/14457836/output.txt)

**Comment by NovTi** [comment]
Thank you for your question. This problem has been reproduced and I am currently working on it

**Comment by NovTi** [comment]
We found this issue is caused by the module import order, mainly the `import torch`, `from bigdl.llm.transformers import AutoModel`, and `from transformers import AutoTokenizer`.

If `import torch` is above `from bigdl.llm.transformers import AutoModel`, then `from transformers import AutoTokenizer`'s and `from bigdl.llm.transformers import AutoModel`'s orders do not matter. All three cases shown below work perfectly:
```python
# case 1
import torch
from transformers import AutoTokenizer
from bigdl.llm.transformers import AutoModel
---------------------------------------------------
# case 2
import torch
from bigdl.llm.transformers import AutoModel
from transformers import AutoTokenizer
---------------------------------------------------
# case 3
from bigdl.llm.transformers import AutoModel
import torch
from transformers import AutoTokenizer
```

However, if `import torch` is below `from bigdl.llm.transformers import AutoModel`, then `from transformers import AutoTokenizer`'s and `from bigdl.llm.transformers import AutoModel`'s orders matter. `from bigdl.llm.transformers import AutoModel` must above the `from transformers import AutoTokenizer`. In the cases shown below, case 1 works but case 2 and case 3 do not.
```python
# case 1, works
from bigdl.llm.transformers import AutoModel
from transformers import AutoTokenizer
import torch
---------------------------------------------------
# case 2, does not work
from transformers import AutoTokenizer
from bigdl.llm.transformers import AutoModel
import torch
---------------------------------------------------
# case 3, does not work
from transformers import AutoTokenizer
import torch
from bigdl.llm.transformers import AutoModel
```

Your code is the case 2 scenario shown above and it gets this error:
![import_error](https://github.com/intel-analytics/BigDL/assets/77518229/517d8dc4-25d7-493a-b292-2b1bc831a1f7)


Therefore, we suggest you put `import torch` above `from transformers import AutoTokenizer`'s and `from bigdl.llm.transformers import AutoModel` like this to solve this error.
```python
import torch
from transformers import AutoTokenizer
from bigdl.llm.transformers import AutoModel
```

**Comment by ganghe** [comment]
Hi NovTi,

Thank for your helps.
The fix works for me.

-Gang
