### ISSUE TITLE
inference Llama-2-7b-chat with W4A16, the latency of next token with 1k input is slower than 2k input

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10598]
benchmark with all-in-one tools:
![image](https://github.com/intel-analytics/ipex-llm/assets/99886928/05385062-f4cd-4880-b959-92ceeaca172a)

**Comment by Fred-cell** [comment]
the performance is ok with generate.py:
 warnings.warn(
=========First token cost 3.5976 s and 4.576171875 GB=========
=========Rest tokens cost average 0.0275 s (329 tokens in all) and 4.576171875 GB=========
=========First token cost 0.4797 s and 4.572265625 GB=========
=========Rest tokens cost average 0.0216 s (329 tokens in all) and 4.572265625 GB=========
=========First token cost 0.4812 s and 4.572265625 GB=========
=========Rest tokens cost average 0.0211 s (329 tokens in all) and 4.572265625 GB=========
=========First token cost 0.4794 s and 4.572265625 GB=========
=========Rest tokens cost average 0.0221 s (329 tokens in all) and 4.572265625 GB=========
=========First token cost 0.4790 s and 4.572265625 GB=========
=========Rest tokens cost average 0.0220 s (329 tokens in all) and 4.572265625 GB=========
=========First token cost 0.4776 s and 4.572265625 GB=========
=========Rest tokens cost average 0.0223 s (329 tokens in all) and 4.572265625 GB=========

**Comment by zhentaocc** [comment]
Didn't observe similar perf discrepancy. 
## steps to reproduce
We did not see the performance regression between the 320 and 319 versions on **W4A16** Llama2-7B. 

**Steps to run**:

1. `cd ~/ipex-llm/python/llm/dev/benchmark/all-in-one`
2. `conda activate zt-perf`
3. Set Quantized KV Cache `export BIGDL_QUANTIZE_KV_CACHE=1`
4. Replace the content of `/home/intel/test/ipex-llm/python/llm/dev/benchmark/all-in-one/config.yaml` to this setting:
```  
repo_id:
  - 'meta-llama/Llama-2-7b-chat-hf'
local_model_hub: '/home/intel/LLM'
warm_up: 1
num_trials: 3
num_beams: 1 # default to greedy search
low_bit: 'sym_int4' # default to use 'sym_int4' (i.e. symmetric int4)
batch_size: 1 # default to 1
in_out_pairs:
  - '1024-512'
  - '2048-512'
test_api:
  - "transformer_int4_gpu"  # on Intel GPU
cpu_embedding: False # whether put embedding to CPU (only avaiable now for gpu win related test_api)
streaming: False # whether output in streaming way (only avaiable now for gpu win related test_api)
```
5. If you need to modify the prompt, for 1024-512, you should modify `prompt/2048.txt`. For 2048-512, modify `prompt/8192.txt`
5. Install the correct bigdl-llm version
6. `bash run-arc.sh`
7. Check the result csv file in the current folder

**Comment by zhentaocc** [comment]
this change causes the perf drop with 1k input. I reverted back in the environment. Please check if it works @Fred-cell 
https://github.com/intel-analytics/ipex-llm/commit/0a40644e001058494f95c2394a507c537b662cd3#diff-3de1ac6e324e143b8b0111a27e9c80ad312baa1531dd2d70c7c06cca16523e2cR1325-R1326
![image](https://github.com/analytics-zoo/nano/assets/90437536/2f2e0f64-4165-4657-a9ca-1cc9bedf297b)

**Comment by zhentaocc** [comment]
# Summary
This issue is confirmed.
And we have found the root cause is we removed upcasting to fp32 on 0320, and this seems harmful to only 1k input in llama.
![image](https://github.com/analytics-zoo/nano/assets/90437536/2f2e0f64-4165-4657-a9ca-1cc9bedf297b)

Here are some observations and issues found during tests
## Observations on ipex-llm version 20240331
1. With A770 from our side, no issue
2. With Fred's A770, 1k input inference has larger latency than 2k
3. With A750 (kernal 6.5), similar issue as Fred's A770
## ipex-llm version 0331&0320 vs 0319 on Fred's A770
1. 1k next token latency was good with 0319
2. 1k next token latency became slow from 0320 (tested on 0320 and 0331)
## some weird issues running on Fred's A770 (Xeon+Arc+Kernel 6.5)
If we run 1k and 2k input separately, the latency of next token was 23ms and 17ms respectively.
While if running them together, 
- run 1k before 2k, both result in ~23ms latency
- run 2k before 1k, both result in ~17ms latency
No idea how this happens.

**Comment by hkvision** [comment]
https://github.com/intel-analytics/ipex-llm/pull/10481
Removing upcast to fp32 for llama seems strangely impacts 1k performance on Fred's machine (as described above by Zhentao).
Any preferences to fix this? Maybe only do not cast for sequences longer than 2k? Or put this to be controlled by IPEX_LLM_LOW_MEM as well? @jason-dai @rnwang04

**Comment by jason-dai** [comment]
> #10481 Removing upcast to fp32 for llama seems strangely impacts 1k performance on Fred's machine (as described above by Zhentao). Any preferences to fix this? Maybe only do not cast for sequences longer than 2k? Or put this to be controlled by IPEX_LLM_LOW_MEM as well? @jason-dai @rnwang04

Maybe also check sequence length for now?
