### ISSUE TITLE
all-in-one with version 2.1.0b1 failed

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#11137]
benchmark llama-3-8b failed:
![image](https://github.com/intel-analytics/ipex-llm/assets/99886928/d219765c-15d4-4a59-b1fb-04fad44049c4)

**Comment by liu-shaojun** [comment]
Will try to reproduce from our side

**Comment by liu-shaojun** [comment]
Hi @Fred-cell, I followed the steps below, cannot reproduce this issue from our side

```
conda create -n llm python=3.10
conda activate llm
pip install --pre --upgrade ipex-llm[xpu] --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
pip install omegaconf
pip install pandas
bash run-arc.sh
```

Can you provide the env information using https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/scripts/env-check.sh?

**Comment by liu-shaojun** [comment]
Hi @Fred-cell, I followed the steps below, cannot reproduce this issue from our side



```
conda create -n llm python=3.10
conda activate llm
pip install --pre --upgrade ipex-llm[xpu]==2.1.0b1 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/

pip install transformers==4.37.0
pip install omegaconf
pip install pandas
bash run-arc.sh
```



Can you provide the env information using https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/scripts/env-check.sh?

**Comment by liu-shaojun** [comment]
According to the offline synchronization with @Fred-cell , the cause of the problem was that oneapi 2024.1 was installed in their environment. We recommended that they install oneapi 2024.0 according to the [guide](https://ipex-llm.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html#id4:~:text=Intel%C2%AE%20oneAPI%20Base%20Toolkit%202024.0%20installation%20methods%3A) and the problem was solved.
