### ISSUE TITLE
Please provide a method to benchmark Multimodal InternVL-4B on MTL‘s iGPU

### ISSUE THREAD

**Issue by zhouzhaojing** [intel-analytics/ipex-llm#11750]
Model link：[OpenGVLab/InternVL2-4B · Hugging Face](https://huggingface.co/OpenGVLab/InternVL2-4B)

**Comment by MeouSker77** [comment]
You can run it following the example in this PR <https://github.com/intel-analytics/ipex-llm/pull/11718>

Fow now, our benchmark script doesn't support multimodal benchmark.

You can set `max_new_tokens=1` to get time `t1`, `t1` is the 1st token latency, 

then set `max_new_tokens=128` to get time `t2`, `(t2 - t1) / 127` is the average 2+ token latency.

We'll support multimodel benchmark in our benchmark script soon

**Comment by zhouzhaojing** [comment]
Thanks clear response for this request.
Now benchmark codes can work on my MTL Ultra 7 155H very well.
We mainly test iGPU and load model to "xpu", obtained:
(loaded prompt and picture)
For int4-sym optimized, we got first token latency: 1.09s , token generation speed: 82.1 tokens/s
For int8-symc,we got first token latency: 1.12s , token generation speed: 43.9 tokens/s

**Comment by MeouSker77** [comment]
glad to hear that you can run benchmark sucessfully, but it's impossible to get 82 token/s when running a 4B model on MTL, it's too fast

maybe you should check whether it really generated 128 tokens when you set `max_new_tokens` to 128, generation will stop earlier if it generated a `eos` token, in such case, the real number of generated tokens is less than 128, so you should compute 2+ token latency with `(t2 - t1) / <real token number>`, or you can set `max_new_tokens` to a smaller number so that it can reach max tokens limit before generating a `eos` token

**Comment by zhouzhaojing** [comment]
Yup, you are right..
Output tokens are not achieving max tokens limitation, so real output tokens are less than the max token limitation I set.
Eventually, wrong token generation time is shorter so token generation speed is faster than the actual speed.
I re-tested these two benchmark, obtained:

For int4-sym optimized, we got first token latency: 1.09s , token generation speed: 16.6 tokens/s
For int8-symc,we got first token latency: 1.12s , token generation speed: 30.5 tokens/s

**Comment by zhouzhaojing** [comment]
BTW, these is a waring still existing ..
Flash attention is not available, I didn't found a way to easily install flash attention on Windows 11.
Please let me know whether Flash attention make an impact on our benchmarks result ?

**Comment by MeouSker77** [comment]
flash attention is only available on CUDA platform, it's not supported on Intel GPU, so you can just ignore this warning
