### ISSUE TITLE
1xArc encounters OOM when running Qwen2-7B, load_in_bit=sym_int4. 

### ISSUE THREAD

**Issue by aprilhu01** [intel-analytics/ipex-llm#12080]
### script
```
  numactl -C 11-15 python ./benchmark_docker_throughput.py \
  --backend vllm \
  --dataset /data/ShareGPT_V3_unfiltered_cleaned_split.json \
  --model Qwen2-7B-Instruct \
  --trust-remote-code \
  --num-prompts 100 \
  --gpu-memory-utilization 0.7 \ #tried 0.6, 0.7, 0.8, 0.9
  --seed 42 \
  --device xpu \
  --dtype float16 \
  --enforce-eager \
  --max-model-len 4096 \
  --max-num-batched-tokens 4096 \
  --load-in-low-bit sym_int4 \
  --tensor-parallel-size 1 
```
### Error log
```
file "/usr/local/lib/python3.11/dist-packages/ipex_llm/transformers/low_bit_linear.py", line 797, in forward
    result = xe_linear.forward_new(x_2d, self.weight.data,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: XPU out of memory. Tried to allocate 130.00 MiB (GPU 0; 15.11 GiB total capacity; 11.09 GiB already allocated; 11.23 GiB reserved in total by PyTorch)

```

**Comment by Uxito-Ada** [comment]
Hi @aprilhu01 ,

This is a normal issue caused by too heavy workloads on limited GPU memory resource. I tried to reproduce it with the same parameters and the request sample [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/vLLM-Serving#3-offline-inferenceservice), but no OOM happens on a single 16G A770 card.

Therefore, I suggest to:

1. Check the prompts in `ShareGPT_V3_unfiltered_cleaned_split.json`, where too long ones will overconsume memory footprints;

3. Tune `max-num-batched-token` and `max-num-seq` in the script, whose explanations can be found [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/vLLM-Serving#service). Lower values can help to reduce the memory consumption.

**Comment by aprilhu01** [comment]
Thanks. Will tune script.
