### ISSUE TITLE
ipex-llm xpu version doesn't work on Lunar Lake 

### ISSUE THREAD

**Issue by HoppeDeng** [intel-analytics/ipex-llm#12268]
Following this link to verify:
https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_windows_gpu.md#verify-installation

It will raise an error:
(ultrachat_back) C:\Users\HB\qwen_ultrachat\ultrachat\trunk\back>python ipex.py
Traceback (most recent call last):
  File "C:\Users\HB\qwen_ultrachat\ultrachat\trunk\back\ipex.py", line 1, in <module>
    import torch
  File "C:\Users\HB\miniforge3\envs\ultrachat_back\lib\site-packages\torch\__init__.py", line 143, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\HB\miniforge3\envs\ultrachat_back\lib\site-packages\torch\lib\backend_with_compiler.dll" or one of its dependencies.

How to solve this problem?

**Comment by Oscilloscope98** [comment]
Hi @HoppeDeng,

There could be several possible cause for this issue. To resolve it, please make sure to:

1. install `ipex_llm[xpu_lnl]` instead of `ipex-llm[xpu]` as we mentioned [here](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_windows_gpu.md#install-ipex-llm).
2. ensure that `libuv` is installed in your conda environment, as mentioned [here](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Overview/install_gpu.md#troubleshooting).

Please let us know for any further problems :)

**Comment by HoppeDeng** [comment]
ipex_llm[xpu_lnl] has fixed this,thanks!
